spring:
  application:
    name: lesson5SpringData

  datasource:
    url: jdbc:postgresql://localhost:5432/postgresdb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  mvc:
    view:
      prefix: /html/
      suffix: .html
    static-path-pattern: /**
    resources:
      static-locations: classpath:/templates/,classpath:/static/
